# Generated by Django 5.0.3 on 2024-04-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='shop_images/default.jpg', null=True, upload_to='shop_images/')),
                ('shopping_complex', models.TextField(blank=True, null=True)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
    ]
