# Generated by Django 5.0.3 on 2024-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopFinder', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
